condition:
  alexey-exists: true
  yanis-exists: true

spring:
  profiles:
    #Доступные профили: Oleg и Peter
    active: Oleg, Peter

logging:
  level:
    root: ERROR


---
spring:
  profiles: Peter


condition:
  yanis-exists: true
